### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by ghost** [mattmemmesheimer/cakephp-3-acl-example#1]
Thanks for the tutorial
I followed it to a tee. Twice.

Well each time I can't login once I've finished. 
It says that the password or user name is wrong. - the error from the login method.
It is doing the sql queries. 
Do you know what is causing this? - I'm using WAMP.

**Comment by paanblogger** [comment]
It seems like , password char length is not enough.Change length to 100

**Comment by mattmemmesheimer** [comment]
@paanblogger fixed this issue in PR #2 by changing the password column's length.  The default CakePHP password hashing algorithm is bcrypt which has a hash length of 60, so technically this column's length could be reduced to 60.
