### ISSUE TITLE
UnauthorizedRedirect error

### ISSUE THREAD

**Issue by aagasi** [mattmemmesheimer/cakephp-3-acl-example#3]
I'm testing this example and i see that in the part that you set the loadcomponent(auth....) with the paremeters, is missing one thing. 
'unauthorizedRedirect' => [
                'controller' => 'Cameras',
                'action' => 'index',
                'prefix' => false
            ],
'authError' => 'forbidden access',
            'flash' => [
                'element' => 'error'
            ]
In the code you are calling de 'Cameras' controller, but that file is missing. And i tried to implement the unauthorized redirect in several ways but i'm not figuring out how to display the error message. I created a contrller and a view but the message 'forbidden access' is not showing up.

Can you help me understand why?

**Comment by Raunter** [comment]
Create the Cameras MVC ou change it, for your OWN.

**Comment by mattmemmesheimer** [comment]
This was due to issue #5, I had incorrectly copy and pasted some code and didn't catch the error.  The `unauthorizedRedirect` key can be set to any controller and action you would like.  I have updated the default to `/users/login`.
